version: "3"
services:
  # Use PostgreSQL as the database
  db:
    image: postgres:15
    networks:
      - database
    volumes:
      - api_cdrplatform_com_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cdrplatform
      POSTGRES_PASSWORD: cdrplatformpassword
      POSTGRES_DB: cdrplatform

  # Use Redis as the cache layer
  cache:
    image: redis:7
    networks:
      - cache
    command:
      # enable persistant storage
      - redis-server
      - --save 60 1
      - --loglevel warning
    volumes:
      - api_cdrplatform_com_cache:/data

  # Development container for VS Code Remote - Containers
  # https://code.visualstudio.com/docs/remote/containers
  # The devcontainer.json file in the .devcontainer folder is used to configure the container.
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - database
      - cache
    volumes:
      - .:/workspaces/api.cdrplatform.com:cached
    # command: sleep infinity
    env_file:
      - .env

volumes:
  api_cdrplatform_com_cache:
  api_cdrplatform_com_db:

networks:
  database:
  cache:
