# Generated by Django 4.1.2 on 2022-10-24 11:30

import cdrplatform.core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cdruser",
            managers=[
                ("objects", cdrplatform.core.managers.CDRUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="removalmethod",
            name="slug",
            field=models.SlugField(default="slug"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="removalpartner",
            name="slug",
            field=models.SlugField(default="slug"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customerinvoice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("chf", "CHF"),
                    ("usd", "USD"),
                    ("gbp", "GBP"),
                    ("eur", "EUR"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="partnerpurchase",
            name="currency",
            field=models.CharField(
                choices=[
                    ("chf", "CHF"),
                    ("usd", "USD"),
                    ("gbp", "GBP"),
                    ("eur", "EUR"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="removalpartner",
            name="currency",
            field=models.CharField(
                choices=[
                    ("chf", "CHF"),
                    ("usd", "USD"),
                    ("gbp", "GBP"),
                    ("eur", "EUR"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="removalrequest",
            name="currency",
            field=models.CharField(
                choices=[
                    ("chf", "CHF"),
                    ("usd", "USD"),
                    ("gbp", "GBP"),
                    ("eur", "EUR"),
                ],
                max_length=3,
            ),
        ),
    ]
