# Generated by Django 4.1.2 on 2022-10-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_partner_name_removalpartner_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="removalmethod",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="removalpartner",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
