# Generated by Django 4.1.2 on 2022-10-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_removalmethod_slug_alter_removalpartner_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyConversionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_currency",
                    models.CharField(
                        choices=[
                            ("chf", "CHF"),
                            ("usd", "USD"),
                            ("gbp", "GBP"),
                            ("eur", "EUR"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        choices=[
                            ("chf", "CHF"),
                            ("usd", "USD"),
                            ("gbp", "GBP"),
                            ("eur", "EUR"),
                        ],
                        max_length=3,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("date_time", models.DateTimeField()),
            ],
        ),
    ]
