# Generated by Django 4.1.2 on 2022-10-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_currencyconversionrate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencyconversionrate",
            options={"ordering": ("-date_time",)},
        ),
    ]
