# Generated by Django 4.1.2 on 2022-10-25 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_currencyconversionrate_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="removalrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
