# Generated by Django 4.1.2 on 2022-10-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_removalrequestitem_variable_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="removalrequestitem",
            name="removal_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="core.removalrequest",
            ),
        ),
    ]
