# Generated by Django 4.1.2 on 2022-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_removalrequestitem_removal_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="removalpartner",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
