# Generated by Django 4.1.2 on 2022-11-08 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_customerorganisation_short_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorganisation",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
