# Generated by Django 4.1.2 on 2022-11-08 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_customerorganisation_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorganisation",
            name="created_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
