# Generated by Django 4.1.2 on 2022-11-08 13:13

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_customerorganisation_created_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerorganisation",
            options={"ordering": ("created_date",)},
        ),
        migrations.AlterField(
            model_name="customerorganisation",
            name="short_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, length=22, max_length=40, prefix="org_", unique=True
            ),
        ),
    ]
