# Generated by Django 4.1.2 on 2022-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_organisationapikey_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerconfirmation",
            name="confirmation_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
