# Generated by Django 4.1.7 on 2023-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_removalrequest_is_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="removalrequest",
            name="is_test",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
